### ISSUE TITLE
vhost work intended on http but not on https

### ISSUE THREAD

**Issue by Ju-Long** [patrickpissurno/fastify-vhost#12]
```
const vhost = require('fastify-vhost');
const fastify = require('fastify') ({
    http2: true,
    logger: true,
    https: {
        allowHTTP1: true,
        key: fs.readFileSync('*'),
        cert: fs.readFileSync('*')
    }
});

const fastifyTest = require('fastify') ({
    http2: true,
    logger: true,
    https: {
        allowHTTP1: true,
        key: fs.readFileSync('*'),
        cert: fs.readFileSync('*')
    }
});

fastify.get('/', async(request, reply) => {
    reply.code(200).send("Hello World")
});

fastifyTest.get('/', async(request, reply) => {
    reply.code(200).send("Hello World From Test")
});

fastify.register(vhost, {
    upstream: "https://example.com:3001",
    host: 'test.example.com'
});

async () => {
    await fastify.listen(443, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
    await fastifyTest.listen(3001, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
}
```

## but if i were to switch to 

```
const vhost = require('fastify-vhost');
const fastify = require('fastify') ({
    logger: true
});

const fastifyTest = require('fastify') ({
    logger: true
});

fastify.get('/', async(request, reply) => {
    reply.code(200).send("Hello World")
});

fastifyTest.get('/', async(request, reply) => {
    reply.code(200).send("Hello World From Test")
});

fastify.register(vhost, {
    upstream: "https://example.com:3001",
    host: 'test.example.com'
});

async () => {
    await fastify.listen(80, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
    await fastifyTest.listen(3001, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
}
```
## please let me know on how to fix this if this is not the intended outcome.

**Comment by patrickpissurno** [comment]
I mean, it does work with https, but not exactly like that.

I'll take a look later to try and reproduce your example scenario, but I'd also want to point out that I think there's a better approach on how to do https in that case.

Only the fastify instance in which this plugin is registered should run on https. The other ones should run on http, on localhost, and everything should work fine (we've been running this exact configuration in production for almost two years now).

You don't really need to worry about security in this case, because as both instances are running on the same host, you're not likely to be prone to a MITM attack or something. In production you may also want to use a firewall to block incoming packets from all ports except for 22 (ssh) and 443 (https).

The above example could be modified to look somewhat like this to make it work:
```js
const vhost = require('fastify-vhost');
const fastify = require('fastify') ({
    logger: true,
    https: {
        key: fs.readFileSync('*'),
        cert: fs.readFileSync('*')
    }
});

const fastifyTest = require('fastify') ({
    logger: true
});

fastify.get('/', async(request, reply) => {
    reply.code(200).send("Hello World")
});

fastifyTest.get('/', async(request, reply) => {
    reply.code(200).send("Hello World From Test")
});

fastify.register(vhost, {
    upstream: "http://example.com:3001",
    host: 'test.example.com'
});

(async () => {
    await fastify.listen(443, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
    await fastifyTest.listen(3001, '0.0.0.0')
    .then((address) => console.log(`server is listening on ${address}`))
    .catch(err => {
        console.log('error starting server: ', err);
        process.exit(1);
    });
})()
```

What you had was something like this (topology):
Top fastify instance (https) -> Test fastify instance (https)

That might not work. This works:
Top fastify instance (http) -> Test fastify instance (http)

And this also works:
Top fastify instance (https) -> Test fastify instance (http)

If you want to use https and have a bunch of fastify instances, just use https in the top-most instance, and leave the others using http.

I don't really know (if and) why the https -> https setup doesn't work, but I might add support for it in the future just for the sake of completeness. But I don't think it's a good idea to set things up that way, as you won't get any extra security benefits (when everything is running on the same machine) and you'd have twice the https overhead.

And by the way, this plugin is intended as a quick and cheap way to optimize resource usage and save money (ie. running a few distinct (low traffic) apps on the same machine). In case you need better performance, or intend to handle a high amount of traffic, you may want to use a real reverse proxy to do this. In that case, I'd recommend taking a look into how to setup Nginx as a reverse proxy for Node. You can also set up virtual servers (vhost) with it. It's just a lot more complicated to setup, and really unecessary for low traffic apps (that's why I created fastify-vhost).

Hope it helps. 

Feel free to ask anything.

Thanks!

**Comment by Ju-Long** [comment]
Alright thank you so much for the quick reply and response, i will check it out later and let you know if it works as intended.

**Comment by Ju-Long** [comment]
it worked! Thank you very much for your time.
